development:
  access_key_id: "DELETED"
  secret_access_key: "DELETED"
  simple_db_consistent_reads: false

production:
  access_key_id: "DELETED"
  secret_access_key: "DELETED"
  simple_db_consistent_reads: true
